version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi-hosting
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings=Server=db;Database=VitalityMasteryTest;User=sa;Password=Strongpassword12345;MultipleActiveResultSets=True;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Strongpassword12345"
      - "ACCEPT_EULA=Y"
    container_name: mssql